// backend/controllers/authController.js

const User = require('../models/User'); // Import User model
const bcrypt = require('bcryptjs'); // Import bcrypt for password hashing
const jwt = require('jsonwebtoken'); // Import jsonwebtoken for JWT generation
const { validationResult } = require('express-validator'); // To access validation results
const crypto = require('crypto');
const nodemailer = require('nodemailer');

// Configure nodemailer
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

// ---- SIGNUP Controller ----
exports.signup = async (req, res) => {
  // 1. Check for validation errors
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    // If there are errors, return 400 Bad Request with the errors array
    return res.status(400).json({ errors: errors.array() });
  }

  // 2. Extract user data from request body
  const { name, email, password, country } = req.body;

  try {
    // 3. Check if user already exists
    let user = await User.findOne({ email }); // Find user by email

    if (user) {
      // If user exists, return 400 Bad Request
      return res.status(400).json({ errors: [{ msg: 'User already exists' }] });
    }

    // 4. Create a new user instance (but don't save yet)
    user = new User({
      name,
      email,
      password, // Plain text password initially
      country, // Include country if it's part of your model and signup form
    });

    // 5. Hash the password before saving
    const salt = await bcrypt.genSalt(10); // Generate a salt (10 rounds is generally recommended)
    user.password = await bcrypt.hash(password, salt); // Hash the password using the salt

    // 6. Save the user to the database
    await user.save();

    // 7. Create JWT Payload
    const payload = {
      user: {
        id: user.id, // Include the user's unique ID (generated by MongoDB)
        // You could add other non-sensitive info like name if needed
      },
    };

    // 8. Sign the JWT
    jwt.sign(
      payload,
      process.env.JWT_SECRET, // Your secret key from .env
      { expiresIn: '5h' }, // Token expiration (e.g., 5 hours) - Adjust as needed
      (err, token) => {
        if (err) throw err; // If signing fails, throw error
        res.status(201).json({ token }); // Send the token back to the client (201 Created)
      }
    );
  } catch (err) {
    console.error('Signup Error:', err.message); // Log the error for debugging
    res.status(500).send('Server error during signup'); // Send generic server error response
  }
};

// ---- LOGIN Controller ----
exports.login = async (req, res) => {
  // 1. Check for validation errors
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }

  // 2. Extract credentials from request body
  const { email, password } = req.body;

  try {
    // 3. Find user by email
    // IMPORTANT: Explicitly select the password field because it's hidden by default (select: false in model)
    let user = await User.findOne({ email }).select('+password');

    if (!user) {
      // If user not found, return 400 Bad Request (generic message for security)
      return res.status(400).json({ errors: [{ msg: 'Invalid Credentials' }] });
    }

    // 4. Compare submitted password with stored hashed password
    const isMatch = await bcrypt.compare(password, user.password); // Compare plain text password with hash

    if (!isMatch) {
      // If passwords don't match, return 400 Bad Request
      return res.status(400).json({ errors: [{ msg: 'Invalid Credentials' }] });
    }

    // 5. User is valid, create JWT Payload
    const payload = {
      user: {
        id: user.id,
      },
    };

    // 6. Sign the JWT
    jwt.sign(
      payload,
      process.env.JWT_SECRET,
      { expiresIn: '5h' }, // Match expiration with signup or use a different one
      (err, token) => {
        if (err) throw err;
        res.json({ token }); // Send the token back (200 OK is default)
      }
    );
  } catch (err) {
    console.error('Login Error:', err.message);
    res.status(500).send('Server error during login');
  }
};

// Forgot Password
exports.forgotPassword = async (req, res) => {
  try {
    const { email } = req.body;
    const user = await User.findOne({ email });

    if (!user) {
      return res.status(404).json({ message: 'User not found' });
    }

    // Generate reset token
    const resetToken = crypto.randomBytes(20).toString('hex');
    const resetTokenExpiry = Date.now() + 3600000; // 1 hour

    user.resetPasswordToken = resetToken;
    user.resetPasswordExpires = resetTokenExpiry;
    await user.save();

    // Send email
    const resetUrl = `${process.env.FRONTEND_URL}/reset-password?token=${resetToken}`;
    const mailOptions = {
      to: user.email,
      from: process.env.EMAIL_USER,
      subject: 'Password Reset',
      text: `You are receiving this because you (or someone else) have requested the reset of the password for your account.\n\n
        Please click on the following link, or paste this into your browser to complete the process:\n\n
        ${resetUrl}\n\n
        If you did not request this, please ignore this email and your password will remain unchanged.\n`
    };

    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: 'Password reset email sent' });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Error sending password reset email' });
  }
};

// Reset Password
exports.resetPassword = async (req, res) => {
  try {
    const { token, password } = req.body;
    const user = await User.findOne({
      resetPasswordToken: token,
      resetPasswordExpires: { $gt: Date.now() }
    });

    if (!user) {
      return res.status(400).json({ message: 'Password reset token is invalid or has expired' });
    }

    // Hash new password
    const salt = await bcrypt.genSalt(10);
    user.password = await bcrypt.hash(password, salt);
    user.resetPasswordToken = undefined;
    user.resetPasswordExpires = undefined;
    await user.save();

    res.status(200).json({ message: 'Password has been reset' });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Error resetting password' });
  }
};